"""The references block — how do I cite this, and whom do I credit?

Every dataset here is built from reads other people generated, and the
`README.txt` in each species directory has always said "please cite
them". This is where that sentence becomes actual citations.

Rendered from the curated files in `references/`, so it is offline and
deterministic like everything else. A BioProject nobody has reviewed
renders as a row with no citation rather than being hidden: the gap is
the thing that gets it filled, and the coverage line counts against it.

Withheld entirely when gate B fails — see `gate.Provenance`. The two
blocked renderings differ because a missing list and a wrong one are
different failures, and neither ever prints a BioProject list: a wrong
list with a warning above it still gets copy-pasted.
"""

from __future__ import annotations

from congen.core.metadata.citations import DOI_URL, Status

from ..format import alert, sentence_list
from ..gate import Provenance
from . import Context, Rendered

HEADING = "## References"

BLOCKED = {
    Provenance.MISSING: [
        "**This dataset cannot yet be cited.**",
        "",
        "No reviewed list of contributing BioProjects exists in this "
        "repository, so there is nothing here to credit the people who "
        "generated the reads. Do not publish analyses of this dataset until "
        "that list exists.",
    ],
    Provenance.WRONG: [
        "**This dataset cannot yet be cited.**",
        "",
        "The recorded list of contributing BioProjects is known to be "
        "incorrect, so it is not reproduced here — a wrong citation list is "
        "worse than none, because it propagates into other people's papers. "
        "Do not publish analyses of this dataset until it is corrected.",
    ],
}

#: Named in the pipeline line even while `tool_citations.yaml` is empty,
#: so the document says what it is built on and what is still missing.
PIPELINE_TOOLS = ("snparcher", "gatk", "genomeark")


def render(context: Context) -> Rendered:
    if not context.verdict.cited:
        return _blocked(context)

    lines = [HEADING, "", _dataset_line(context), ""]
    lines += _bioprojects(context)
    pipeline = _pipeline(context)
    if pipeline:
        lines += ["", pipeline]
    return Rendered(lines)


def _blocked(context: Context) -> Rendered:
    verdict = context.verdict
    body = list(BLOCKED[verdict.provenance])
    fired = sentence_list([f"`{check}`" for check in verdict.fired])
    if fired:
        means = "these mean" if len(verdict.fired) > 1 else "that means"
        body += [
            "",
            f"Reported by {fired} — see [`VALIDATION.md`](VALIDATION.md) for "
            f"what {means} and how to fix it.",
        ]
    kind = "WARNING" if verdict.provenance is Provenance.MISSING else "CAUTION"
    return Rendered([HEADING, "", *alert(kind, body)])


def _dataset_line(context: Context) -> str:
    accession = context.dataset.accession or "this accession"
    return (
        f"These calls were produced by the VGP Conservation Genomics project "
        f"and published on GenomeArk under `{accession}`. The reads they were "
        "called from were generated by other people; please cite the "
        "BioProjects below."
    )


def _bioprojects(context: Context) -> list[str]:
    counts = context.bioprojects()
    if not counts:
        return ["*No contributing BioProjects are recorded for this species.*"]

    index = context.citations
    ordered = sorted(counts, key=lambda p: (-counts[p], p))
    lines = [_coverage(context, counts), ""]

    for project in ordered:
        entry = index.get(project) if index else None
        samples = counts[project]
        weight = f"{samples} sample{'' if samples == 1 else 's'}"
        title = (entry.title if entry else "") or ""
        head = f"- **[{project}](https://www.ncbi.nlm.nih.gov/bioproject/{project})** · {weight}"
        if title:
            head += f" · {title}"
        lines.append(head)

        if entry and entry.status is Status.CONFIRMED and entry.dois:
            for doi in entry.dois:
                reference = entry.reference(doi) or doi
                lines.append(f"  - {reference} [{doi}]({DOI_URL}{doi})")
        elif entry and entry.status is Status.NOT_FOUND:
            lines.append("  - *no publication found*")
        else:
            lines.append("  - *citation not yet reviewed*")
    return lines


def _coverage(context: Context, counts: dict[str, int]) -> str:
    """The honesty metric, and the thing that gets the gaps filled.

    Measured in samples as well as BioProjects, because one uncited
    project carrying forty samples matters more than one carrying a
    single sample.
    """
    index = context.citations
    cited = [p for p in counts if index and index.get(p).is_citable]
    total_samples = sum(counts.values())
    cited_samples = sum(counts[p] for p in cited)
    if not total_samples:
        return f"Citations are recorded for {len(cited)} of {len(counts)} BioProjects."
    return (
        f"Citations are recorded for {cited_samples} of {total_samples} samples "
        f"({len(cited)} of {len(counts)} BioProjects)."
    )


def _pipeline(context: Context) -> str:
    """One short line, naming what is missing rather than staying silent.

    These are bibliographic claims about other people's work, so nothing
    here is generated — `tool_citations.yaml` ships with every entry
    `pending` and a human fills it. Saying so keeps the gap visible; a
    document that simply omitted the pipeline would let it stay missing.
    """
    tools = context.citations.tools if context.citations else {}
    citable = [tools[key] for key in PIPELINE_TOOLS if key in tools and tools[key].is_citable]
    if citable:
        return "Pipeline: " + "; ".join(
            f"{tool.name} — {tool.citation or tool.doi}" for tool in citable
        )
    return (
        "Variants were called with snpArcher and GATK against a Vertebrate "
        "Genomes Project assembly. Citations for the pipeline and the "
        "reference assembly are not recorded yet "
        "(`references/tool_citations.yaml`)."
    )
