"""BioProject citations: a review queue and a settled record.

**Two files, because they answer different questions.**

`references/citations-review.md` is the queue. It holds only BioProjects
that still need a human, ordered by how many samples depend on them, and
it empties as the work gets done. A first draft kept everything in one
file on the theory that reviewed blocks get shorter — but that still
means scanning past two hundred settled entries to find the ninety that
need attention, which is not a queue.

`references/bioproject_citations.tsv` is the record: one compact line per
decided BioProject, machine-written, greppable, and boring to diff.

**Reviewing is deletion, and there is one rule: every line is a claim, so
delete the ones that are not true.**

    ## PRJNA323498 — 147 samples · birds/hirundo-rustica
    Hirundo rustica Genome sequencing and assembly
    The University of Colorado · [BioProject](...)

    <!-- considered: 10.3390/ijms27167433 10.1111/mec.70074 -->

    - NOT YET REVIEWED
    - ★ [10.1111/mec.70074](https://doi.org/10.1111/mec.70074) — Schield DR et al. ...
    - [10.3390/ijms27167433](https://doi.org/10.3390/ijms27167433) — Lombardo G et al. ...
    - NO PUBLICATION FOUND

Click a DOI, skim, delete what is false. The judgement is whether the
paper is the one the data was *generated for* — a later paper reusing
someone else's reads needs no credit here, and reuse is what a second
search hit usually is. Two papers genuinely sharing that role happens,
rarely, and then both lines stay.

`NOT YET REVIEWED` is the single bit separating a decision from an
untouched block, so no status field is needed anywhere. Editing the queue
on GitHub commits the decision, which is why the mechanic is deletion
rather than a checkbox: task-list checkboxes are read-only in repository
markdown files.

A `★` marks a candidate whose author affiliations include the
BioProject's submitting organisation — a decent proxy for "generated by
the same people", and the strongest signal available for free. Starred
candidates are rendered first.
"""

from __future__ import annotations

import enum
import json
import re
from dataclasses import dataclass, field
from pathlib import Path

from congen.core.metadata.models import LoadIssue

QUEUE_FILE = Path("references") / "citations-review.md"
RECORD_FILE = Path("references") / "bioproject_citations.json"
TOOLS_FILE = Path("references") / "tool_citations.yaml"

UNREVIEWED_MARKER = "NOT YET REVIEWED"

#: Searched, and nothing found. **Not** a claim that a paper will never
#: exist: whether one is coming is a statement about the submitter's
#: intentions, and we are almost never the submitter. This says only what
#: we looked for and did not see, which is ours to say.
#:
#: An earlier design split this into "yet" and "expected" so "expected"
#: could be permanent. Wrong twice over. The distinction was unanswerable
#: by anyone but the submitter, and it was unnecessary — the evidence
#: trigger already stops the queue nagging, because a BioProject with no
#: candidates has nothing unseen to show. Worse, "expected" would have
#: suppressed the one notification worth having: a paper appearing for a
#: project someone had written off.
NOT_FOUND_MARKER = "NO PUBLICATION FOUND"

#: Marks a candidate whose author affiliations include the BioProject's
#: submitting organisation. A hint, not a verdict — see
#: `literature.affiliation_matches`.
MATCH_STAR = "★"

#: Written by `--propose` and invisible when rendered, so a reviewer
#: deleting list items never disturbs it. It is what makes "a candidate
#: nobody has seen" decidable: rejected = considered - kept.
CONSIDERED_PREFIX = "<!-- considered:"

NCBI_BIOPROJECT = "https://www.ncbi.nlm.nih.gov/bioproject/"
DOI_URL = "https://doi.org/"

#: The record is JSON, not a table.
#:
#: A BioProject can have several accepted DOIs, each with its own
#: reference text and its own verification state — and flat columns
#: cannot hold that. `PRJNA323498` already has three accepted DOIs
#: against a single `reference` column, so the table was lossy the day
#: it was written. This is the same failure that killed the original
#: review CSV, one level down.
#:
#: Hand-readability is not a cost here: the record is machine-written and
#: the queue is the human surface.

_HEADING = re.compile(r"^##\s+(?P<accession>PRJ[A-Z]{2}\d+)\b")
#: A DOI in a markdown link, or bare so a reviewer can paste one in.
#: The star is **captured**, not merely tolerated. Every rewrite of the
#: queue goes through parse -> render, so a star the parser discards is a
#: star the next `--collect` deletes. That is exactly what happened: one
#: `--collect` stripped all 166 of them from the committed queue.
_DOI_LINE = re.compile(
    rf"^-\s+(?P<star>{MATCH_STAR})?\s*(?:\[(?P<linked>10\.[^\]]+)\]|(?P<bare>10\.\S+))"
)
_MARKER_LINE = re.compile(
    rf"^-\s+(?P<marker>{UNREVIEWED_MARKER}|{NOT_FOUND_MARKER})\b"
)
_CONSIDERED = re.compile(r"^<!--\s*considered:(?P<dois>[^>]*?)-->")


class Status(enum.Enum):
    #: A paper was accepted. **Final.** A later search hit on the same
    #: BioProject is usually data *reuse*, and reuse does not need
    #: crediting — so reopening a confirmed entry would offer a citation
    #: nobody should add. The genuine multi-paper case is rare and is
    #: handled at review time, when both candidates are already on screen.
    CONFIRMED = "confirmed"
    #: Searched; nothing found. Reopens on new evidence — see
    #: `NOT_FOUND_MARKER` and `reopen`.
    NOT_FOUND = "not_found"
    UNREVIEWED = "unreviewed"

    @property
    def is_reviewed(self) -> bool:
        return self is not Status.UNREVIEWED

    @property
    def reopens_on_new_evidence(self) -> bool:
        """Only `not_found` does.

        Derived, not asked. A reviewer is never made to judge whether a
        paper is *coming* — they say what they found, and this decides
        what to do about it later.
        """
        return self is Status.NOT_FOUND

    def __str__(self) -> str:
        return self.value


@dataclass
class Entry:
    bioproject: str
    status: Status = Status.UNREVIEWED
    #: More than one is legitimate, which the old single-column CSV could
    #: not express.
    dois: list[str] = field(default_factory=list)
    references: dict[str, str] = field(default_factory=dict)
    title: str = ""
    submitter: str = ""
    #: DOIs a reviewer looked at and deleted. Kept so a later search can
    #: tell a genuinely new candidate from one already rejected.
    rejected: list[str] = field(default_factory=list)
    #: Every DOI `--propose` put in front of a reviewer, from the block's
    #: hidden comment. Only meaningful while the block is in the queue.
    considered: list[str] = field(default_factory=list)
    #: DOIs whose affiliations match the submitter. Presentation only.
    starred: set[str] = field(default_factory=set)
    #: DOIs confirmed to resolve through doi.org. Tracked per DOI so
    #: `--verify` checks each one once rather than re-checking 300 every
    #: run, and so a reviewer's hand-typed typo is caught exactly once.
    verified: set[str] = field(default_factory=set)
    #: Weight, so the queue explains its own order.
    samples: int = 0
    species: list[str] = field(default_factory=list)
    line: int | None = None

    def unseen(self, dois) -> list[str]:
        """Candidates neither accepted nor already rejected."""
        known = set(self.dois) | set(self.rejected)
        return [doi for doi in dois if doi not in known]

    @property
    def is_citable(self) -> bool:
        return self.status is Status.CONFIRMED and bool(self.dois)

    def reference(self, doi: str) -> str:
        return self.references.get(doi, "")

    @property
    def best_reference(self) -> str:
        for doi in self.dois:
            if self.references.get(doi):
                return self.references[doi]
        return ""


@dataclass
class CitationIndex:
    entries: dict[str, Entry] = field(default_factory=dict)
    issues: list[LoadIssue] = field(default_factory=list)
    #: Decided in the queue but not yet filed into the record. Housekeeping,
    #: not an error: reviewing works without ever running the tool.
    unfiled: list[str] = field(default_factory=list)

    def __len__(self) -> int:
        return len(self.entries)

    def get(self, bioproject: str) -> Entry:
        """Always an `Entry`; an unknown BioProject is `unreviewed`."""
        return self.entries.get(bioproject) or Entry(bioproject=bioproject)

    def status_of(self, bioproject: str) -> Status:
        return self.get(bioproject).status

    def needs_review(self, bioprojects) -> list[str]:
        return sorted({a for a in bioprojects if not self.status_of(a).is_reviewed})

    def citable(self, bioprojects) -> list[str]:
        return sorted({a for a in bioprojects if self.get(a).is_citable})

    @property
    def queued(self) -> list[Entry]:
        return [e for e in self.entries.values() if not e.status.is_reviewed]

    @property
    def decided(self) -> list[Entry]:
        return [e for e in self.entries.values() if e.status.is_reviewed]


# -- the record -------------------------------------------------------------


def parse_record(text: str, path: Path | None = None) -> dict[str, Entry]:
    """Read the settled record. Tolerant: a malformed entry is skipped."""
    try:
        payload = json.loads(text) if text.strip() else {}
    except json.JSONDecodeError:
        return {}
    out: dict[str, Entry] = {}
    for accession, body in (payload.items() if hasattr(payload, "items") else ()):
        if not hasattr(body, "get"):
            continue
        try:
            status = Status(str(body.get("status") or ""))
        except ValueError:
            continue
        entry = Entry(
            bioproject=str(accession),
            status=status,
            title=str(body.get("title") or ""),
            submitter=str(body.get("submitter") or ""),
            rejected=[str(d) for d in body.get("rejected") or []],
        )
        for citation in body.get("citations") or []:
            if not hasattr(citation, "get"):
                continue
            doi = str(citation.get("doi") or "").strip()
            if not doi:
                continue
            entry.dois.append(doi)
            reference = str(citation.get("reference") or "")
            if reference:
                entry.references[doi] = reference
            if citation.get("verified"):
                entry.verified.add(doi)
        out[str(accession)] = entry
    return out


def render_record(entries) -> str:
    payload = {}
    for entry in sorted(entries, key=lambda e: e.bioproject):
        body = {"status": entry.status.value}
        if entry.title:
            body["title"] = entry.title
        if entry.submitter:
            body["submitter"] = entry.submitter
        if entry.dois:
            body["citations"] = [
                {
                    "doi": doi,
                    "reference": entry.reference(doi),
                    "verified": doi in entry.verified,
                }
                for doi in entry.dois
            ]
        if entry.rejected:
            body["rejected"] = list(entry.rejected)
        payload[entry.bioproject] = body
    # ensure_ascii=False so a title keeps its real characters. Crossref
    # returns typographic hyphens and accented names, and escaping them
    # makes a file people occasionally read much harder to scan.
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


# -- the queue --------------------------------------------------------------


def parse_queue(text: str, path: Path | None = None) -> tuple[dict[str, Entry], list[LoadIssue]]:
    entries: dict[str, Entry] = {}
    issues: list[LoadIssue] = []
    current: Entry | None = None
    prose: list[str] = []
    saw: set[str] = set()

    def close() -> None:
        nonlocal current
        if current is None:
            return
        # rejected = everything put in front of the reviewer that is no
        # longer here. Derivable only because `considered` survives in a
        # comment the reviewer has no reason to touch.
        current.rejected = [
            doi for doi in current.considered if doi not in current.dois
        ]
        if current.status is not Status.UNREVIEWED:
            if current.dois:
                current.status = Status.CONFIRMED
            elif NOT_FOUND_MARKER in saw:
                current.status = Status.NOT_FOUND
            else:
                # Every line deleted: nothing is asserted, so nothing is
                # decided. Never read silence as a citation, and never as
                # a settled "no publication".
                current.status = Status.UNREVIEWED
                issues.append(
                    LoadIssue(
                        code="C010",
                        message=(
                            f"{current.bioproject}: every line was deleted, so "
                            f"nothing is asserted — keep a DOI or "
                            f"'{NOT_FOUND_MARKER}'"
                        ),
                        path=path,
                        line=current.line,
                    )
                )
        entries[current.bioproject] = current
        current = None
        saw.clear()

    for number, raw in enumerate(text.replace("\r\n", "\n").split("\n"), start=1):
        line = raw.rstrip()
        heading = _HEADING.match(line)
        if heading:
            close()
            current = _entry_from_heading(heading.group("accession"), line, number)
            prose = []
            continue
        if current is None:
            continue

        considered = _CONSIDERED.match(line)
        if considered:
            current.considered = considered.group("dois").split()
            continue

        marker = _MARKER_LINE.match(line)
        if marker:
            found_marker = marker.group("marker")
            if found_marker == UNREVIEWED_MARKER:
                current.status = Status.UNREVIEWED
            else:
                saw.add(found_marker)
            continue

        found = _DOI_LINE.match(line)
        if found:
            doi = (found.group("linked") or found.group("bare")).strip().rstrip(").,;")
            if doi not in current.dois:
                current.dois.append(doi)
            current.references[doi] = _reference_text(line)
            if found.group("star"):
                current.starred.add(doi)
            continue

        if line and not line.startswith(("-", "#", "<!--", "|")):
            prose.append(line)
            _absorb_prose(current, prose)

    close()
    return entries, issues


def _entry_from_heading(accession: str, line: str, number: int) -> Entry:
    # Starts as "decided" and is demoted by the marker, so a block whose
    # marker was deleted is read as a decision.
    entry = Entry(bioproject=accession, line=number, status=Status.CONFIRMED)
    samples = re.search(r"(\d+)\s+samples?", line)
    if samples:
        entry.samples = int(samples.group(1))
    entry.species = re.findall(r"\b([a-z]+/[a-z0-9-]+)\b", line)
    return entry


def _reference_text(line: str) -> str:
    _, sep, rest = line.partition("—")
    return rest.strip() if sep else ""


def _absorb_prose(entry: Entry, prose: list[str]) -> None:
    entry.title = prose[0]
    if len(prose) > 1:
        entry.submitter = prose[1].split("·")[0].strip()


def load_citations(root: Path) -> CitationIndex:
    """The record, overlaid with whatever the queue says.

    The queue wins: a decision made there but not yet filed is still a
    decision, so review does not depend on anyone running the tool.
    """
    index = CitationIndex()
    try:
        index.entries.update(parse_record((root / RECORD_FILE).read_text("utf-8")))
    except (FileNotFoundError, OSError):
        pass
    try:
        queued, issues = parse_queue((root / QUEUE_FILE).read_text("utf-8"), root / QUEUE_FILE)
    except (FileNotFoundError, OSError):
        return index
    index.issues += issues
    for accession, entry in queued.items():
        settled = index.entries.get(accession)
        if settled is not None and settled.status.is_reviewed and not entry.status.is_reviewed:
            # Already filed; a stale queue block must not un-decide it.
            continue
        index.entries[accession] = entry
        if entry.status.is_reviewed:
            index.unfiled.append(accession)
    index.unfiled.sort()
    return index


QUEUE_PREAMBLE = f"""<!-- Written by `congen citations --propose`. Reviewed by hand; see below. -->

# BioProject citations awaiting review

Every dataset here is built from reads other people generated. This is
the queue of BioProjects nobody has credited yet.

## How to review

**Every line below is a claim. Delete the ones that are not true.**

Click a DOI, skim the paper, then:

| If | Keep only |
|---|---|
| a candidate is the paper the data was generated for | that DOI line |
| two papers genuinely share that role | both DOI lines — rare, but it happens |
| none of them is | `{NOT_FOUND_MARKER}` |
| you have not looked yet | `{UNREVIEWED_MARKER}` (leave the block alone) |

Judge whether a paper is the one the data was **generated for**, not
merely one that used it. A later paper reusing someone else's reads does
not need crediting here.

`{NOT_FOUND_MARKER}` says what we searched for and did not find. It is
deliberately **not** a claim that a paper will never exist — whether one
is coming is a statement about the submitter's intentions, and we are
almost never the submitter. Data is routinely released ahead of its
paper, so a block recorded this way comes back to this queue the moment a
search turns up a DOI nobody has already rejected. A confirmed one does
not come back.

A {MATCH_STAR} means the paper lists the BioProject's submitting
organisation among its author affiliations — which is a decent proxy for
"generated by the same people". A hint, not a verdict: it is wrong often
enough to be worth one glance rather than trust. Starred candidates are
listed first.

Editing this file on GitHub commits the decision, so the commit records
who decided what. Run `congen citations --collect` to file the finished
blocks into `bioproject_citations.tsv`; they then disappear from here, so
this file only ever shows work that remains.

Ordered by how many samples depend on each BioProject, worst first.
"""


def render_entry(entry: Entry) -> list[str]:
    plural = "" if entry.samples == 1 else "s"
    heading = f"## {entry.bioproject} — {entry.samples} sample{plural}"
    if entry.species:
        heading += " · " + " · ".join(entry.species)
    lines = [heading, ""]
    if entry.title:
        lines.append(entry.title)
    trailer = [entry.submitter] if entry.submitter else []
    trailer.append(f"[BioProject]({NCBI_BIOPROJECT}{entry.bioproject})")
    lines += [" · ".join(trailer), ""]

    considered = entry.considered or (entry.dois + entry.rejected)
    if considered:
        lines += [f"{CONSIDERED_PREFIX} {' '.join(considered)} -->", ""]

    if entry.status is Status.UNREVIEWED:
        lines.append(f"- {UNREVIEWED_MARKER}")
    # Starred first: a reviewer reads top-down, so the candidate carrying
    # the submitter's own affiliation should be the first one they see.
    for doi in sorted(entry.dois, key=lambda d: d not in entry.starred):
        reference = entry.reference(doi)
        star = f"{MATCH_STAR} " if doi in entry.starred else ""
        lines.append(
            f"- {star}[{doi}]({DOI_URL}{doi})" + (f" — {reference}" if reference else "")
        )
    if entry.status is not Status.CONFIRMED:
        lines.append(f"- {NOT_FOUND_MARKER}")
    lines.append("")
    return lines


def render_queue(entries) -> str:
    ordered = sorted(
        entries, key=lambda e: (-e.samples, -len(e.species), e.bioproject)
    )
    lines = [QUEUE_PREAMBLE.rstrip(), ""]
    if not ordered:
        lines += ["Nothing awaiting review. Every BioProject has been decided.", ""]
    for entry in ordered:
        lines += render_entry(entry)
    return "\n".join(lines).rstrip() + "\n"


def merge_proposals(queued: dict[str, Entry], proposals) -> tuple[dict[str, Entry], int]:
    """Add candidates to queued blocks without disturbing a hand edit.

    Only ever fills: a DOI the queue does not have is appended, blank
    metadata is filled, and weight is refreshed because it describes the
    corpus rather than the decision. Nothing is removed, so deleting a
    wrong candidate is permanent — which is the whole mechanic.
    """
    merged = dict(queued)
    changed = 0
    for proposal in proposals:
        existing = merged.get(proposal.bioproject)
        if existing is None:
            merged[proposal.bioproject] = proposal
            changed += 1
            continue
        touched = False
        if not existing.status.is_reviewed:
            for doi in proposal.dois:
                if doi not in existing.dois:
                    existing.dois.append(doi)
                    existing.references[doi] = proposal.reference(doi)
                    touched = True
            for name in ("title", "submitter"):
                if not getattr(existing, name) and getattr(proposal, name):
                    setattr(existing, name, getattr(proposal, name))
                    touched = True
        if (existing.samples, existing.species) != (proposal.samples, proposal.species):
            existing.samples = proposal.samples
            existing.species = proposal.species
            touched = True
        changed += 1 if touched else 0
    return merged, changed


# -- tool and assembly citations -------------------------------------------

TOOL_KEYS = ("snparcher", "gatk", "genomeark", "assembly")


@dataclass(frozen=True)
class ToolCitation:
    key: str
    name: str = ""
    status: str = "pending"
    doi: str = ""
    citation: str = ""
    url: str = ""

    @property
    def is_citable(self) -> bool:
        return self.status == "confirmed" and bool(self.citation or self.doi)


def parse_tool_citations(text: str, path: Path | None = None) -> dict[str, ToolCitation]:
    from congen.core.metadata.writers import load_yaml_roundtrip

    try:
        data = load_yaml_roundtrip(text) or {}
    except Exception:  # noqa: BLE001 - a broken file must not break rendering
        return {}
    out: dict[str, ToolCitation] = {}
    for key, value in (data.items() if hasattr(data, "items") else ()):
        if not hasattr(value, "get"):
            continue
        out[str(key)] = ToolCitation(
            key=str(key),
            name=str(value.get("name") or ""),
            status=str(value.get("status") or "pending"),
            doi=str(value.get("doi") or ""),
            citation=str(value.get("citation") or ""),
            url=str(value.get("url") or ""),
        )
    return out


def load_tool_citations(root: Path) -> dict[str, ToolCitation]:
    path = root / TOOLS_FILE
    try:
        return parse_tool_citations(path.read_text("utf-8"), path)
    except (FileNotFoundError, OSError):
        return {}


def reopen(entry: Entry, dois) -> Entry | None:
    """A `not_found` entry to put back in the queue, given fresh results.

    `None` unless the search turned up a DOI neither already accepted nor
    already rejected — and `None` always for a `confirmed` entry, because
    a later hit on the same BioProject is usually data reuse, which needs
    no credit.

    **Evidence, not elapsed time, is the trigger.** A calendar rule would
    either nag about hopeless cases or sit on a paper that appeared
    yesterday, and would make the queue depend on when it was run — the
    same reason the validator makes staleness a property of the inputs
    rather than of the date.
    """
    if not entry.status.reopens_on_new_evidence:
        return None
    unseen = entry.unseen(dois)
    if not unseen:
        return None
    revived = Entry(
        bioproject=entry.bioproject,
        status=Status.UNREVIEWED,
        dois=list(unseen),
        rejected=list(entry.rejected),
        title=entry.title,
        submitter=entry.submitter,
        samples=entry.samples,
        species=list(entry.species),
    )
    # Spans old and new, so a second rejection is remembered too.
    revived.considered = list(dict.fromkeys(entry.rejected + unseen))
    return revived


def merge_into_record(existing: Entry | None, decided: Entry) -> Entry:
    """Fold a decided queue block into whatever the record already holds.

    The queue owns the decision — which DOIs are accepted — but the
    record owns what has been *learned* about them: whether each DOI
    resolves, and the reference text `--verify` fetched. Replacing
    wholesale discards that, which is what happened the first time a
    block was filed twice: four verifications and three references gone,
    silently.

    So the queue wins on the decision and the record wins on everything
    it knows that the queue cannot.
    """
    if existing is None:
        return decided
    merged = Entry(
        bioproject=decided.bioproject,
        status=decided.status,
        dois=list(decided.dois),
        title=decided.title or existing.title,
        submitter=decided.submitter or existing.submitter,
        # A DOI rejected once stays rejected, so a later search does not
        # re-offer it.
        rejected=sorted(set(existing.rejected) | set(decided.rejected)),
        samples=decided.samples,
        species=list(decided.species),
        starred=set(decided.starred),
    )
    for doi in merged.dois:
        reference = decided.reference(doi) or existing.reference(doi)
        if reference:
            merged.references[doi] = reference
        if doi in existing.verified:
            merged.verified.add(doi)
    return merged
