"""Render validation reports as Markdown.

These files are documentation. Someone deciding whether to rely on a
species' metadata reads the first three lines and nothing else, so the
verdict, the date and the accession go there and everything else is
detail underneath.

Fully generated — unlike a README, nothing here is hand-written, so no
managed blocks.
"""

from __future__ import annotations

from congen.core.status import PublicationState
from congen.core.validation_record import ReportState, ValidationRecord

GENERATED_NOTE = "<!-- generated by congen-metadata-tools; do not edit by hand -->"

SEVERITY_LABEL = {"error": "error", "warn": "warning", "info": "note"}

STATE_BLURB = {
    ReportState.PASS: "Metadata agrees with the data published on GenomeArk.",
    ReportState.PASS_WITH_WARNINGS: (
        "Metadata agrees with the data published on GenomeArk, with points to note."
    ),
    ReportState.FAIL: "Problems were found. See below before relying on this metadata.",
    ReportState.PENDING: (
        "Not yet validated against published data. This is an expected state: "
        "metadata is often committed before a run is published."
    ),
    ReportState.STALE: (
        "The metadata changed after the verdict below was produced, so that "
        "verdict no longer describes these files."
    ),
}


def _headline(record: ValidationRecord, species_name: str) -> list[str]:
    lines = [f"# Validation — {species_name}", ""]

    if record.state is ReportState.STALE:
        lines.append(
            f"**STALE** · {record.stale_reason or 'inputs changed'} "
            f"· last validated {record.validated_at[:10]}"
        )
        lines.append("")
        lines.append(STATE_BLURB[ReportState.STALE])
        return lines

    accession = (record.data or {}).get("accession")
    bits = [f"**{record.state.value}**", record.validated_at[:10]]
    if accession:
        bits.append(accession)
    lines.append(" · ".join(bits))
    lines.append("")
    lines.append(STATE_BLURB[record.state])
    return lines


def _facts(record: ValidationRecord) -> str | None:
    status = record.status or {}
    counts = status.get("counts") or {}
    parts = []
    if counts.get("sheet_samples"):
        parts.append(f"{counts['sheet_samples']} samples in the sheet")
    if counts.get("bams"):
        parts.append(f"{counts['bams']} BAMs")
    if counts.get("vcf_samples"):
        parts.append(f"{counts['vcf_samples']} samples in the VCF")
    state = status.get("state")
    if state and state != PublicationState.COMPLETE.value:
        parts.append(f"publication {state}")
    return " · ".join(parts) if parts else None


def _finding_lines(
    record: ValidationRecord, severity: str, *, checks_href: str | None = None
) -> list[str]:
    out = []
    for finding in record.findings:
        if finding["severity"] != severity:
            continue
        identifier = finding["id"]
        label = (
            f"[{identifier}]({checks_href}#{identifier.lower()})"
            if checks_href
            else identifier
        )
        out.append(f"- **{label}** {finding['message']}")
        if finding.get("detail"):
            out.append(f"  - {finding['detail']}")
        if finding.get("path"):
            where = finding["path"]
            if finding.get("line"):
                where = f"{where}:{finding['line']}"
            out.append(f"  - at `{where}`")
    return out


def render_species_report(
    record: ValidationRecord, species_name: str, *, checks_href: str | None = None
) -> str:
    """``checks_href`` links each finding ID to the generated CHECKS.md."""
    lines = _headline(record, species_name)

    facts = _facts(record)
    if facts and record.state is not ReportState.STALE:
        lines += ["", facts]

    # A stale report's findings describe files that have since changed.
    # They belong in the superseded block, not presented as current.
    if record.state is not ReportState.STALE:
        for severity, heading in (
            ("error", "Errors"),
            ("warn", "Warnings"),
            ("info", "Notes"),
        ):
            body = _finding_lines(record, severity, checks_href=checks_href)
            if body:
                lines += ["", f"## {heading}", ""] + body

    skipped = [f for f in record.findings if f["severity"] == "skipped"]
    lines += ["", "## What was checked", ""]
    scope = f"{len(record.checks_run)} of {record.checks_available} checks"
    if record.is_partial_selection:
        scope += " — **a partial selection**, so this report is not a full validation"
    lines.append(f"- {scope}")
    if skipped:
        reasons: dict[str, int] = {}
        for finding in skipped:
            reasons[finding.get("detail") or "unavailable"] = (
                reasons.get(finding.get("detail") or "unavailable", 0) + 1
            )
        for reason, count in sorted(reasons.items(), key=lambda kv: -kv[1]):
            lines.append(f"- {count} skipped: {reason}")

    data = record.data or {}
    lines += ["", "## Provenance", ""]
    lines.append(f"- validated `{record.validated_at}` by congen-metadata-tools {record.tool_version}")
    if data.get("accession"):
        lines.append(f"- data: `{data['accession']}`" + ("" if data.get("published") else " (not published)"))
    for name, digest in sorted(record.inputs.items()):
        lines.append(f"- `{name}` `{digest}`")

    if record.superseded:
        previous = record.superseded
        lines += [
            "",
            "<details>",
            f"<summary>Superseded result — {previous['state']}, {previous['validated_at'][:10]}</summary>",
            "",
        ]
        for finding in previous.get("findings", []):
            if finding["severity"] == "skipped":
                continue
            label = SEVERITY_LABEL.get(finding["severity"], finding["severity"])
            lines.append(f"- {label} **{finding['id']}** {finding['message']}")
        lines += ["", "</details>"]

    lines += ["", GENERATED_NOTE, ""]
    return "\n".join(lines)


STATE_ORDER = (
    ReportState.FAIL,
    ReportState.STALE,
    ReportState.PASS_WITH_WARNINGS,
    ReportState.PENDING,
    ReportState.PASS,
)


def render_corpus_report(
    records: list[tuple[str, ValidationRecord]],
    *,
    validated_at: str,
    tool_version: str,
    corpus_findings: list[dict] | None = None,
) -> str:
    """The repo-root table: every species, one line each."""
    lines = ["# Validation status", ""]
    lines.append(f"Generated `{validated_at}` by congen-metadata-tools {tool_version}.")
    lines.append("")

    counts = {state: 0 for state in ReportState}
    for _, record in records:
        counts[record.state] += 1
    lines += ["| State | Species |", "|---|---|"]
    for state in STATE_ORDER:
        if counts[state]:
            lines.append(f"| **{state.value}** | {counts[state]} |")
    lines.append("")

    if corpus_findings:
        lines += ["## Corpus", ""]
        for finding in corpus_findings:
            lines.append(f"- **{finding['id']}** {finding['message']}")
        lines.append("")

    lines += ["## Species", "", "| Species | State | Validated | Summary |", "|---|---|---|---|"]
    for path, record in sorted(records, key=lambda kv: kv[0]):
        errors = sum(1 for f in record.findings if f["severity"] == "error")
        warnings = sum(1 for f in record.findings if f["severity"] == "warn")
        summary = ", ".join(
            part
            for part in (
                f"{errors} error{'s' if errors != 1 else ''}" if errors else "",
                f"{warnings} warning{'s' if warnings != 1 else ''}" if warnings else "",
            )
            if part
        ) or "—"
        link = f"[{record.subject}]({path}/VALIDATION.md)"
        lines.append(
            f"| {link} | {record.state.value} | {record.validated_at[:10]} | {summary} |"
        )

    lines += ["", GENERATED_NOTE, ""]
    return "\n".join(lines)


CHECKS_FILE = "CHECKS.md"

TIER_TITLES = {
    "R": "Repository self-consistency",
    "G": "Publication on GenomeArk",
    "S": "Sample identity",
    "F": "Reference identity and canonicality",
    "P": "Config against recorded provenance",
    "E": "External accessions (NCBI SRA)",
}

SEVERITY_NOTE = {
    "error": "a defect: do not rely on this metadata until it is resolved",
    "warn": "worth attention, but not disqualifying",
    "info": "recorded for reference; no action implied",
}


def _docstring_paragraphs(text: str | None) -> list[str]:
    """Every paragraph, reflowed.

    Not just the first: the checks put the headline in paragraph one and
    the reason it matters in paragraph two, and the reason is the part a
    reader chasing an ID actually needs.
    """
    if not text:
        return []
    out = []
    for block in text.strip().split("\n\n"):
        joined = " ".join(line.strip() for line in block.splitlines() if line.strip())
        if joined:
            out.append(joined)
    return out


def render_checks_reference(checks, *, tool_version: str) -> str:
    """The lookup table for the IDs that appear in validation reports.

    Generated from the registry so it cannot drift from the code — the
    failure mode for a hand-maintained reference is that it quietly stops
    describing what the tool does.
    """
    import inspect

    lines = [
        "# Validation checks",
        "",
        "Every finding in a `VALIDATION.md` carries an ID. This is what they mean.",
        "",
        f"Generated from congen-metadata-tools {tool_version}; {len(list(checks))} checks.",
        "",
        "Severities:",
        "",
    ]
    for severity, note in SEVERITY_NOTE.items():
        lines.append(f"- **{severity}** — {note}")
    lines += [
        "",
        "A check may also be *skipped*, which means its inputs were unavailable —",
        "most often because the species has no published data yet. A skipped check",
        "is not a pass; the report says how many were skipped and why.",
        "",
    ]

    by_tier: dict[str, list] = {}
    for check in checks:
        by_tier.setdefault(check.tier, []).append(check)

    for tier in ("R", "G", "S", "F", "P", "E"):
        group = sorted(by_tier.get(tier, []), key=lambda c: c.id)
        if not group:
            continue
        lines += [f"## {TIER_TITLES.get(tier, tier)}", ""]
        for check in group:
            lines.append(f"### {check.id}")
            lines.append("")
            lines.append(f"**{check.severity.value}** — {check.summary}")
            for paragraph in _docstring_paragraphs(inspect.getdoc(check.func)):
                lines += ["", paragraph]
            lines.append("")

    lines += [GENERATED_NOTE, ""]
    return "\n".join(lines)
